import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/Theme";
import Navbar from "./components/Bar/Navbar";
import { Toaster } from "react-hot-toast";

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.variable} antialiased bg-base-300 text-base-content h-screen overflow-hidden`}
      >
        <ThemeProvider>
          <Navbar />
          <div className="flex flex-col h-[calc(100vh-64px)]">{children}</div>
          <Toaster position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
